/* ============================================================
   ROBOTS.TXT — generated by Next.js at /robots.txt
   Controls what Google can and cannot crawl.
   ============================================================ */

export default function robots() {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        // Block pages that should never be indexed
        disallow: [
          "/api/",
          "/otp/",
          "/payment/",
          "/payment-confirmed/",
          "/booking-success/",
          "/profile/",
        ],
      },
    ],
    sitemap: "https://www.mmmiles.com/sitemap.xml",
    host: "https://www.mmmiles.com",
  };
}
