export const cities = [
  {
    slug: "chennai", name: "Chennai", state: "Tamil Nadu", active: true,
    phone: "+918050953607", whatsapp: "918050953607", email: "support@mmmiles.com",
    hub: "Nolambur, Ambattur", priceFrom: 799,
    coordinates: { lat: 13.0827, lng: 80.2707 },
    seoDescription: "Self drive car rental in Chennai with zero deposit and unlimited km.",
    popularDestinations: [
      { name: "Pondicherry", distance: "162 km", time: "3 hrs" },
      { name: "Mahabalipuram", distance: "58 km", time: "1.5 hrs" },
      { name: "ECR Beach", distance: "30 km", time: "45 mins" },
      { name: "Ooty", distance: "540 km", time: "9 hrs" },
      { name: "Kodaikanal", distance: "465 km", time: "8 hrs" },
      { name: "Yercaud", distance: "325 km", time: "5.5 hrs" },
      { name: "Vellore", distance: "140 km", time: "2.5 hrs" },
      { name: "Tirupati", distance: "140 km", time: "2.5 hrs" },
    ],
    areas: [
      { slug: "omr", name: "OMR", fullName: "Old Mahabalipuram Road (OMR)", landmarks: ["Sholinganallur", "Perungudi", "Thoraipakkam", "Karapakkam"] },
      { slug: "ecr", name: "ECR", fullName: "East Coast Road (ECR)", landmarks: ["Akkarai", "Muttukadu", "Kovalam", "Injambakkam"] },
      { slug: "anna-nagar", name: "Anna Nagar", fullName: "Anna Nagar", landmarks: ["Anna Nagar Tower", "Shanthi Colony", "Thirumangalam"] },
      { slug: "velachery", name: "Velachery", fullName: "Velachery", landmarks: ["Phoenix Marketcity", "Velachery MRTS", "Vijayanagar"] },
      { slug: "t-nagar", name: "T Nagar", fullName: "T Nagar", landmarks: ["Pondy Bazaar", "Panagal Park", "Usman Road"] },
      { slug: "adyar", name: "Adyar", fullName: "Adyar", landmarks: ["Adyar Bridge", "Besant Nagar", "Elliot's Beach"] },
      { slug: "porur", name: "Porur", fullName: "Porur", landmarks: ["Porur Lake", "DLF Ramapuram", "Mount Poonamallee Road"] },
      { slug: "tambaram", name: "Tambaram", fullName: "Tambaram", landmarks: ["Tambaram Railway Station", "Pallavaram", "Vandalur Zoo"] },
      { slug: "chrompet", name: "Chrompet", fullName: "Chrompet", landmarks: ["Chrompet Market", "Pallavaram Radial Road"] },
      { slug: "ambattur", name: "Ambattur", fullName: "Ambattur", landmarks: ["Ambattur Industrial Estate", "Nolambur", "Mogappair East"] },
      { slug: "nungambakkam", name: "Nungambakkam", fullName: "Nungambakkam", landmarks: ["Nungambakkam High Road", "US Consulate"] },
      { slug: "guindy", name: "Guindy", fullName: "Guindy", landmarks: ["Guindy National Park", "SIDCO", "IIT Madras Gate"] },
      { slug: "mogappair", name: "Mogappair", fullName: "Mogappair", landmarks: ["Mogappair West", "CMBT", "Ambattur IE Road"] },
      { slug: "ashok-nagar", name: "Ashok Nagar", fullName: "Ashok Nagar", landmarks: ["100 Feet Road", "KK Nagar boundary"] },
      { slug: "kk-nagar", name: "KK Nagar", fullName: "KK Nagar", landmarks: ["KK Nagar Park", "Jawaharlal Nehru Road"] },
      { slug: "mylapore", name: "Mylapore", fullName: "Mylapore", landmarks: ["Kapaleeshwarar Temple", "San Thome Cathedral"] },
      { slug: "madipakkam", name: "Madipakkam", fullName: "Madipakkam", landmarks: ["Madipakkam Main Road", "Kovilambakkam"] },
      { slug: "sholinganallur", name: "Sholinganallur", fullName: "Sholinganallur", landmarks: ["Sholinganallur Junction", "Perumbakkam"] },
      { slug: "perungudi", name: "Perungudi", fullName: "Perungudi", landmarks: ["Perungudi Toll", "Tidel Park"] },
      { slug: "thoraipakkam", name: "Thoraipakkam", fullName: "Thoraipakkam", landmarks: ["Thoraipakkam Junction", "OMR Food Street"] },
      { slug: "pallikaranai", name: "Pallikaranai", fullName: "Pallikaranai", landmarks: ["Pallikaranai Marsh", "Grand Mall"] },
      { slug: "perambur", name: "Perambur", fullName: "Perambur", landmarks: ["Perambur Railway Station", "Kolathur"] },
      { slug: "kilpauk", name: "Kilpauk", fullName: "Kilpauk", landmarks: ["Kilpauk Medical College", "Kilpauk Garden"] },
      { slug: "egmore", name: "Egmore", fullName: "Egmore", landmarks: ["Chennai Central", "Egmore Museum"] },
      { slug: "chennai-central", name: "Chennai Central", fullName: "Chennai Central", landmarks: ["Central Railway Station", "Broadway"] },
      { slug: "royapettah", name: "Royapettah", fullName: "Royapettah", landmarks: ["Royapettah Clock Tower", "Haddows Road"] },
      { slug: "vadapalani", name: "Vadapalani", fullName: "Vadapalani", landmarks: ["Vadapalani Bus Terminus", "Kaliamman Temple"] },
      { slug: "valasaravakkam", name: "Valasaravakkam", fullName: "Valasaravakkam", landmarks: ["Valasaravakkam Bus Stop", "Virugambakkam"] },
      { slug: "poonamallee", name: "Poonamallee", fullName: "Poonamallee", landmarks: ["Poonamallee Bypass", "Sriperumbudur Road"] },
      { slug: "saidapet", name: "Saidapet", fullName: "Saidapet", landmarks: ["Saidapet Bridge", "Little Mount"] },
      { slug: "thiruvottiyur", name: "Thiruvottiyur", fullName: "Thiruvottiyur", landmarks: ["Thiruvottiyur Thermal Station", "Ennore Port Road"] },
      { slug: "avadi", name: "Avadi", fullName: "Avadi", landmarks: ["Avadi Railway Station", "Integral Coach Factory"] },
      { slug: "kolathur", name: "Kolathur", fullName: "Kolathur", landmarks: ["Kolathur Market", "Villivakkam"] },
      { slug: "kodambakkam", name: "Kodambakkam", fullName: "Kodambakkam", landmarks: ["Kodambakkam High Road", "Mahalingapuram"] },
      { slug: "virugambakkam", name: "Virugambakkam", fullName: "Virugambakkam", landmarks: ["Virugambakkam Bus Stop", "Arcot Road"] },
      { slug: "nanganallur", name: "Nanganallur", fullName: "Nanganallur", landmarks: ["Nanganallur Metro", "Alandur"] },
      { slug: "chromepet", name: "Chromepet", fullName: "Chromepet", landmarks: ["Chromepet Railway Station", "GST Road"] },
      { slug: "medavakkam", name: "Medavakkam", fullName: "Medavakkam", landmarks: ["Medavakkam Junction", "Keelkattalai"] },
      { slug: "nerkundram", name: "Nerkundram", fullName: "Nerkundram", landmarks: ["Nerkundram Junction", "Koyambedu"] },
      { slug: "selaiyur", name: "Selaiyur", fullName: "Selaiyur", landmarks: ["Selaiyur Bus Stop", "Perungalathur"] },
    ],
  },
  {
    slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu", active: true,
    phone: "+918050953607", whatsapp: "918050953607", email: "support@mmmiles.com",
    hub: "Gandhipuram", priceFrom: 799,
    coordinates: { lat: 11.0168, lng: 76.9558 },
    seoDescription: "Self drive car rental in Coimbatore with zero deposit and unlimited km.",
    popularDestinations: [
      { name: "Ooty", distance: "86 km", time: "2 hrs" },
      { name: "Kodaikanal", distance: "175 km", time: "3.5 hrs" },
      { name: "Munnar", distance: "155 km", time: "3 hrs" },
      { name: "Valparai", distance: "101 km", time: "2.5 hrs" },
      { name: "Coonoor", distance: "56 km", time: "1.5 hrs" },
      { name: "Pollachi", distance: "40 km", time: "1 hr" },
      { name: "Palakkad", distance: "60 km", time: "1.5 hrs" },
    ],
    areas: [
      { slug: "gandhipuram", name: "Gandhipuram", fullName: "Gandhipuram", landmarks: ["Central Bus Stand", "Big Bazaar Street"] },
      { slug: "rs-puram", name: "RS Puram", fullName: "RS Puram", landmarks: ["DB Road", "Avinashi Road"] },
      { slug: "peelamedu", name: "Peelamedu", fullName: "Peelamedu", landmarks: ["Coimbatore Airport", "CODISSIA"] },
      { slug: "saravanampatti", name: "Saravanampatti", fullName: "Saravanampatti", landmarks: ["Tidel Park", "Nirmala College"] },
      { slug: "singanallur", name: "Singanallur", fullName: "Singanallur", landmarks: ["Singanallur Lake", "Avinashi Road"] },
      { slug: "ganapathy", name: "Ganapathy", fullName: "Ganapathy", landmarks: ["Ganapathy Bus Stop", "Pappanaickenpalayam"] },
      { slug: "thudiyalur", name: "Thudiyalur", fullName: "Thudiyalur", landmarks: ["Thudiyalur Road", "Vadavalli"] },
      { slug: "vadavalli", name: "Vadavalli", fullName: "Vadavalli", landmarks: ["Vadavalli Junction", "Mettupalayam Road"] },
      { slug: "kovaipudur", name: "Kovaipudur", fullName: "Kovaipudur", landmarks: ["Kovaipudur Road", "Marudhamalai Hills"] },
      { slug: "podanur", name: "Podanur", fullName: "Podanur", landmarks: ["Podanur Railway Junction", "Irugur Road"] },
      { slug: "kuniyamuthur", name: "Kuniyamuthur", fullName: "Kuniyamuthur", landmarks: ["Kuniyamuthur Bus Stop", "Pollachi Road"] },
      { slug: "ukkadam", name: "Ukkadam", fullName: "Ukkadam", landmarks: ["Ukkadam Bus Stand", "Ukkadam Lake"] },
      { slug: "ondipudur", name: "Ondipudur", fullName: "Ondipudur", landmarks: ["Ondipudur Toll", "Avinashi Road"] },
      { slug: "sulur", name: "Sulur", fullName: "Sulur", landmarks: ["Sulur Air Force", "Avinashi Road"] },
      { slug: "mettupalayam", name: "Mettupalayam", fullName: "Mettupalayam", landmarks: ["Mettupalayam Railway Station", "Ooty Base"] },
      { slug: "pollachi", name: "Pollachi", fullName: "Pollachi", landmarks: ["Pollachi Junction", "Anamalai Tiger Reserve"] },
      { slug: "vellalore", name: "Vellalore", fullName: "Vellalore", landmarks: ["Vellalore Road", "SIHS Colony"] },
      { slug: "kavundampalayam", name: "Kavundampalayam", fullName: "Kavundampalayam", landmarks: ["Kavundampalayam Junction", "Lakshmi Mills"] },
      { slug: "rathinapuri", name: "Rathinapuri", fullName: "Rathinapuri", landmarks: ["Rathinapuri Road", "KK Pudur"] },
      { slug: "pappanaickenpalayam", name: "Pappanaickenpalayam", fullName: "Pappanaickenpalayam", landmarks: ["Pappanaickenpalayam Bus Stop", "TNEB Road"] },
      { slug: "saravanampatty", name: "Saravanampatty", fullName: "Saravanampatty", landmarks: ["IT Park", "CODISSIA Trade Fair"] },
      { slug: "civil-aerodrome", name: "Civil Aerodrome", fullName: "Civil Aerodrome", landmarks: ["Coimbatore Airport Area", "Race Course"] },
      { slug: "hopes-college", name: "Hopes College", fullName: "Hopes College Area", landmarks: ["Hope College", "Peelamedu"] },
      { slug: "annur", name: "Annur", fullName: "Annur", landmarks: ["Annur Town", "Mettupalayam Road"] },
      { slug: "vedapatti", name: "Vedapatti", fullName: "Vedapatti", landmarks: ["Vedapatti Road", "Western Ghats Entry"] },
    ],
  },
  {
    slug: "bangalore", name: "Bangalore", state: "Karnataka", active: true,
    phone: "+918050953607", whatsapp: "918050953607", email: "support@mmmiles.com",
    hub: "Whitefield", priceFrom: 899,
    coordinates: { lat: 12.9716, lng: 77.5946 },
    seoDescription: "Self drive car rental in Bangalore with zero deposit and unlimited km.",
    popularDestinations: [
      { name: "Mysore", distance: "150 km", time: "3 hrs" },
      { name: "Coorg", distance: "250 km", time: "5 hrs" },
      { name: "Chikmagalur", distance: "245 km", time: "5 hrs" },
      { name: "Ooty", distance: "270 km", time: "5.5 hrs" },
      { name: "Pondicherry", distance: "315 km", time: "6 hrs" },
      { name: "Hampi", distance: "340 km", time: "6 hrs" },
      { name: "Wayanad", distance: "285 km", time: "5.5 hrs" },
      { name: "Nandi Hills", distance: "60 km", time: "1.5 hrs" },
    ],
    areas: [
      { slug: "whitefield", name: "Whitefield", fullName: "Whitefield", landmarks: ["ITPL", "Forum Value Mall", "Marathahalli"] },
      { slug: "koramangala", name: "Koramangala", fullName: "Koramangala", landmarks: ["Forum Mall", "Sony World Junction", "80 Feet Road"] },
      { slug: "hsr-layout", name: "HSR Layout", fullName: "HSR Layout", landmarks: ["HSR BDA Complex", "Agara Lake", "27th Main"] },
      { slug: "electronic-city", name: "Electronic City", fullName: "Electronic City", landmarks: ["Infosys Campus", "Electronic City Phase 1"] },
      { slug: "indiranagar", name: "Indiranagar", fullName: "Indiranagar", landmarks: ["100 Feet Road", "CMH Road", "Defence Colony"] },
      { slug: "marathahalli", name: "Marathahalli", fullName: "Marathahalli", landmarks: ["Marathahalli Bridge", "Outer Ring Road"] },
      { slug: "bellandur", name: "Bellandur", fullName: "Bellandur", landmarks: ["Bellandur Lake", "Outer Ring Road"] },
      { slug: "sarjapur-road", name: "Sarjapur Road", fullName: "Sarjapur Road", landmarks: ["Sarjapur Junction", "Wipro Gate"] },
      { slug: "jp-nagar", name: "JP Nagar", fullName: "JP Nagar", landmarks: ["JP Nagar Phase 1", "Bannerghatta Road"] },
      { slug: "bannerghatta-road", name: "Bannerghatta Road", fullName: "Bannerghatta Road", landmarks: ["Bannerghatta Park", "JP Nagar"] },
      { slug: "btm-layout", name: "BTM Layout", fullName: "BTM Layout", landmarks: ["BTM 1st Stage", "Madiwala"] },
      { slug: "silk-board", name: "Silk Board", fullName: "Silk Board", landmarks: ["Silk Board Junction", "Hosur Road"] },
      { slug: "hebbal", name: "Hebbal", fullName: "Hebbal", landmarks: ["Hebbal Flyover", "Manyata Tech Park"] },
      { slug: "yelahanka", name: "Yelahanka", fullName: "Yelahanka", landmarks: ["Yelahanka New Town", "Air Force Station"] },
      { slug: "mg-road", name: "MG Road", fullName: "MG Road", landmarks: ["Brigade Road", "Commercial Street", "Cubbon Park"] },
      { slug: "banashankari", name: "Banashankari", fullName: "Banashankari", landmarks: ["Banashankari Temple", "Gandhi Bazaar"] },
      { slug: "jayanagar", name: "Jayanagar", fullName: "Jayanagar", landmarks: ["4th Block", "Jayanagar Shopping Complex"] },
      { slug: "rajajinagar", name: "Rajajinagar", fullName: "Rajajinagar", landmarks: ["Rajajinagar Market", "Chord Road"] },
      { slug: "malleswaram", name: "Malleswaram", fullName: "Malleswaram", landmarks: ["Malleswaram Market", "18th Cross"] },
      { slug: "yeshwanthpur", name: "Yeshwanthpur", fullName: "Yeshwanthpur", landmarks: ["Yeshwanthpur Metro", "IKEA"] },
      { slug: "peenya", name: "Peenya", fullName: "Peenya", landmarks: ["Peenya Industrial Area", "Tumkur Road"] },
      { slug: "kr-puram", name: "KR Puram", fullName: "KR Puram", landmarks: ["KR Puram Railway Station", "Tin Factory"] },
      { slug: "cv-raman-nagar", name: "CV Raman Nagar", fullName: "CV Raman Nagar", landmarks: ["CV Raman Nagar Metro", "Old Madras Road"] },
      { slug: "mahadevapura", name: "Mahadevapura", fullName: "Mahadevapura", landmarks: ["Mahadevapura Junction", "EPIP Zone"] },
      { slug: "kadugodi", name: "Kadugodi", fullName: "Kadugodi", landmarks: ["Kadugodi Tree Park", "Whitefield Road"] },
      { slug: "varthur", name: "Varthur", fullName: "Varthur", landmarks: ["Varthur Lake", "Sarjapur Road"] },
      { slug: "domlur", name: "Domlur", fullName: "Domlur", landmarks: ["Domlur Layout", "Embassy Golf Links"] },
      { slug: "richmond-town", name: "Richmond Town", fullName: "Richmond Town", landmarks: ["Richmond Road", "Lalbagh"] },
      { slug: "basavanagudi", name: "Basavanagudi", fullName: "Basavanagudi", landmarks: ["Bull Temple", "Gandhi Bazaar"] },
      { slug: "ulsoor", name: "Ulsoor", fullName: "Ulsoor", landmarks: ["Ulsoor Lake", "Old Madras Road"] },
    ],
  },
];

export function getCityBySlug(slug) {
  return cities.find((c) => c.slug === slug) || null;
}

export function getAreaBySlug(citySlug, areaSlug) {
  const city = getCityBySlug(citySlug);
  if (!city) return null;
  return city.areas.find((a) => a.slug === areaSlug) || null;
}

export function getActiveCities() {
  return cities.filter((c) => c.active);
}
